var TopLevel = {
"AudioContext" : function () {},
"clearInterval" : function () {},
"connect" : function () {},
"console" : function () {},
"createBufferSource" : function () {},
"createGain" : function () {},
"createOscillator" : function () {},
"currentTime" : function () {},
"decodeAudioData" : function () {},
"document" : function () {},
"log" : function () {},
"open" : function () {},
"response" : function () {},
"send" : function () {},
"setInterval" : function () {},
"start" : function () {},
"stop" : function () {},
"write" : function () {},
"XMLHttpRequest" : function () {}
}
