var TopLevel = {
"AudioContext" : function () {},
"clearInterval" : function () {},
"connect" : function () {},
"console" : function () {},
"createBufferSource" : function () {},
"createGain" : function () {},
"createOscillator" : function () {},
"decodeAudioData" : function () {},
"document" : function () {},
"escape" : function () {},
"history" : function () {},
"location" : function () {},
"log" : function () {},
"Object" : function () {},
"open" : function () {},
"pathname" : function () {},
"pushState" : function () {},
"response" : function () {},
"search" : function () {},
"send" : function () {},
"setInterval" : function () {},
"start" : function () {},
"stop" : function () {},
"unescape" : function () {},
"XMLHttpRequest" : function () {}
}
